### ISSUE TITLE
1.1.0 Crouch State version on Modrinth is not a mod

### ISSUE THREAD

**Issue by mintynoura** [TonyGamer/Berry-Fix#1]
The .jar is only a kilobyte of an empty meta-inf file and thus has no mod to load

**Comment by AdalynBlack** [comment]
Oh, thanks for the notice
I must have uploaded the wrong jar

**Comment by AdalynBlack** [comment]
I have uploaded version 1.1.1 to Modrinth, which now actually contains the mod code lol
